[programs.localnet]
cofre = "Cofre5DxTYsWtWKrby3hLVg8pM5RePf96sCa7HJMwDeZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "devnet"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"
# test-inspect = "yarn test:inspect"
