[paths]
artifacts = "./.captain/artifacts/"
program_keypairs = "./.captain/program_keypairs"
[networks.testnet]
deployer = "./.captain/deployers/testnet/deployer.json"
upgrade_authority = "~/.config/solana/id.json"
url = "https://api.testnet.solana.com"
ws_url = "wss://api.testnet.solana.com"

[networks.mainnet]
deployer = "./.captain/deployers/mainnet/deployer.json"
upgrade_authority = "~/.config/solana/id.json"
url = "https://api.mainnet-beta.solana.com"
ws_url = "wss://api.mainnet-beta.solana.com"

[networks.devnet]
deployer = "./.captain/deployers/devnet/deployer.json"
upgrade_authority = "~/.config/solana/id.json"
url = "https://api.devnet.solana.com"
ws_url = "wss://api.devnet.solana.com"

[networks.localnet]
deployer = "./.captain/deployers/localnet/deployer.json"
upgrade_authority = "~/.config/solana/id.json"
url = "http://127.0.0.1:8899"
ws_url = "ws://127.0.0.1:9000"
